development:
  adapter: postgresql
  database: pepsi-ruby
  username: postgres
  password: 
  host: localhost
test:
  adapter: postgresql
  database: pepsi-ruby-test
  username: postgres
  password: 
  host: localhost